version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
      - pip install -r requirements.txt  

  build:
    commands:
      - echo "Running build steps"

  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "Artifacts are ready"

artifacts:
  files:
    - '**/*'  
  discard-paths: no  

cache:
  paths:
    - 'pip-cache/**/*'
